// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYq8yGrcplJCGVbAWf2r0KPQUy6HwMXe8',
    appId: '1:677421742212:web:9e8710e99f4f7038b72ad1',
    messagingSenderId: '677421742212',
    projectId: 'tadcurso1',
    authDomain: 'tadcurso1.firebaseapp.com',
    databaseURL: 'https://tadcurso1-default-rtdb.firebaseio.com',
    storageBucket: 'tadcurso1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiZBNUBxG38nM5cFinJXwBx91qvWxKw44',
    appId: '1:677421742212:android:bf9055ce7b13a1cab72ad1',
    messagingSenderId: '677421742212',
    projectId: 'tadcurso1',
    databaseURL: 'https://tadcurso1-default-rtdb.firebaseio.com',
    storageBucket: 'tadcurso1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDATU9xLHA2dci9px72j_xmsYZLdYchPdg',
    appId: '1:677421742212:ios:f88488dc9f8032c6b72ad1',
    messagingSenderId: '677421742212',
    projectId: 'tadcurso1',
    databaseURL: 'https://tadcurso1-default-rtdb.firebaseio.com',
    storageBucket: 'tadcurso1.firebasestorage.app',
    iosBundleId: 'com.tad.primerapp',
  );
}
